<?php
return [
                'ADMIN_PERMISSION',
                //USER
                'MANAGE_USER',
                'CREATE_USER',
                'EDIT_USER',
                'DELETE_USER',
                //PROPERTY
                'MANAGE_PROPERTY',
                'CREATE_PROPERTY',
                'EDIT_PROPERTY',
                'DELETE_PROPERTY',
                //UNIT
                'MANAGE_UNIT',
                'CREATE_UNIT',
                'EDIT_UNIT',
                'DELETE_UNIT',
                //TENANT
                'MANAGE_TENANT',
                'CREATE_TENANT',
                'EDIT_TENANT',
                'DELETE_TENANT',
                //MAINTAINER
                'MANAGE_MAINTAINER',
                'CREATE_MAINTAINER',
                'EDIT_MAINTAINER',
                'DELETE_MAINTAINER',
                //MAINTENANCE_REQUEST
                'MANAGE_MAINTENANCE_REQUEST',
                'CREATE_MAINTENANCE_REQUEST',
                'EDIT_MAINTENANCE_REQUEST',
                'DELETE_MAINTENANCE_REQUEST',
                //CONTACT
                'MANAGE_CONTACT',
                'CREATE_CONTACT',
                'EDIT_CONTACT',
                'DELETE_CONTACT',
                //LEASE
                'MANAGE_LEASE',
                'CREATE_LEASE',
                'EDIT_LEASE',
                'DELETE_LEASE',
            ];
?>